name: fin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  android_path_provider: ^0.3.1
  uuid: ^4.5.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  intl_utils: ^2.0.0

flutter:
  uses-material-design: true
